service: contact-serverless-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    SECRET: ${file(.env.json):SECRET}

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline