service: travl-miranda-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    SECRET: ${file(.env.json):SECRET}
    MONGO_URI: ${file(.env.json):MONGO_URI}
    # SECRET: ${env:SECRET}
    # MONGO_URI: ${env.):MONGO_URI}

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline